---
# Needed to modify this role for become_user
# See https://github.com/marvel-nccr/quantum-mobile/issues/67
#- src: gantsign.default-web-browser
#  version: 3.1.0
- src: marvel-nccr.ansible_prerequisites
  version: v0.1.0
- src: marvel-nccr.current_user
  version: v0.1.0
- src: marvel-nccr.add_user
  version: v0.2.1
- src: marvel-nccr.simulationbase
  version: v0.1.1
- src: marvel-nccr.ubuntu_desktop
  version: v0.1.0
- src: marvel-nccr.quantum_mobile_customizations
  version: v0.1.0
- src: marvel-nccr.editors
  version: v0.1.0
- src: marvel-nccr.slurm
  version: v0.1.1
- src: marvel-nccr.quantum_espresso
  version: v1.0.0
- src: marvel-nccr.cp2k
  version: v1.0.0
- src: marvel-nccr.lammps
  version: v1.0.0
- src: uchida.miniconda
  version: master
- src: marvel-nccr.dl_poly
  version: master
- src: marvel-nccr.vmd
  version: master
